# Generated by Django 5.2.1 on 2025-06-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetroGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('console', models.CharField(choices=[('nes', 'NES'), ('snes', 'SNES'), ('md', 'Mega Drive'), ('ps1', 'PlayStation 1'), ('nds', 'Nintendo 3DS')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('game_cover', models.ImageField(upload_to='retrogames/covers/')),
            ],
        ),
    ]
