# Generated by Django 5.2.1 on 2025-06-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrogame',
            name='console',
            field=models.CharField(choices=[('nes', 'NES'), ('snes', 'SNES'), ('n64', 'Nintendo 64'), ('ps1', 'PlayStation 1'), ('nds', 'Nintendo 3DS')], max_length=10),
        ),
    ]
