# Generated by Django 5.2.1 on 2025-06-03 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='passport',
            name='pass_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Between',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations.product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(through='relations.Between', to='relations.product'),
        ),
    ]
