# Generated by Django 5.2.1 on 2025-06-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exoplanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('radius_km', models.FloatField()),
                ('orbit_type', models.CharField(choices=[('circular', 'Kreisförmig'), ('elliptical', 'Elliptisch'), ('hyperbolic', 'Hyperbolisch')], max_length=50)),
                ('habitable', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
