# Generated by Django 5.2.1 on 2025-06-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('species', models.CharField(choices=[('human', 'Mensch'), ('vulcan', 'Vulkanier'), ('klingon', 'Klingone'), ('andorian', 'Andorianer'), ('borg', 'Borg (nur Drohnen mit Empfehlung)')], max_length=20)),
                ('preferred_branch', models.CharField(choices=[('command', 'Kommando'), ('engineering', 'Technik'), ('science', 'Wissenschaft'), ('medical', 'Medizinisch')], max_length=20)),
                ('online_profile', models.URLField(blank=True)),
                ('skills', models.JSONField()),
                ('motivation', models.TextField(blank=True)),
                ('date_of_birth', models.DateField()),
                ('upload_cv', models.FileField(blank=True, null=True, upload_to='uploads/cvs/')),
                ('agree_to_terms', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
