# Generated by Django 5.2.1 on 2025-06-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VillainGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_alias', models.CharField(max_length=100)),
                ('gear_name', models.CharField(max_length=100)),
                ('gear_type', models.CharField(choices=[('weapon', 'Waffe'), ('vehicle', 'Fahrzeug'), ('robot', 'Roboter'), ('tool', 'Werkzeug'), ('ai', 'Künstliche Intelligenz')], max_length=20)),
                ('origin_year', models.PositiveIntegerField()),
                ('explosive', models.BooleanField(default=False)),
                ('last_maintenance', models.DateField()),
                ('power_rating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
