# Generated by Django 5.2.1 on 2025-06-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nerd_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villaingear',
            name='last_maintenance',
        ),
    ]
