# Generated by Django 5.2.1 on 2025-06-06 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerd_forms', '0002_remove_villaingear_last_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WandLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('wand_length_cm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wand_core', models.CharField(choices=[('phoenix', 'Phönixfeder'), ('dragon', 'Drachenherzfaser'), ('unicorn', 'Einhornhaar'), ('thestral', 'Thestralschweif')], max_length=20)),
                ('has_dark_mark', models.BooleanField(default=False)),
                ('patronus_description', models.TextField(blank=True)),
                ('license_requested_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('magical_law_acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-license_requested_on'],
            },
        ),
    ]
