# Generated by Django 5.2.1 on 2025-06-12 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('views_count', models.IntegerField(default=10)),
                ('is_published', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('F', 'Weiblich'), ('M', 'Männlich'), ('D', 'Divers')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='Fragetext')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Veröffentlichungsdatum')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='Antworttext')),
                ('votes', models.IntegerField(default=0, verbose_name='Stimmen')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Zugehörige Frage')),
            ],
        ),
    ]
