# Generated by Django 5.2.1 on 2025-05-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('views_count', models.IntegerField(default=10)),
                ('is_published', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('F', 'Weiblich'), ('M', 'Männlich'), ('D', 'Divers')])),
            ],
        ),
    ]
